customCommands:
  - key: 'E'
    description: 'Add empty commit'
    context: 'files'
    command: 'git commit --allow-empty -m "empty commit"'
    loadingText: 'Committing empty commit...'
  - key: '<c-a>'
    description: 'Bump Major'
    context: 'files'
    command: 'pnpm version major --no-git-tag-version'
    loadingText: 'Bumping major version...'
  - key: '<c-b>'
    description: 'Bump Minor'
    context: 'files'
    command: 'pnpm version minor --no-git-tag-version'
    loadingText: 'Bumping minor version...'
  - key: '<c-c>'
    description: 'Bump Patch'
    context: 'files'
    command: 'pnpm version patch --no-git-tag-version'
    loadingText: 'Bumping patch version...'
  - key: '<c-d>'
    description: 'Bump Prerelease'
    context: 'files'
    prompts:
      - type: 'input'
        title: 'Is there a preid? (Leave empty for default)'
        key: 'preid'
        initialValue: ''
    command: 'pnpm version prerelease --preid {{.Form.preid}} --no-git-tag-version'
    loadingText: 'Bumping prerelease version...'
git:
  skipHookPrefix: WIP
